--create comment table
create table comment (
    comment_id bigint generated by default as identity,
    created_at timestamp not null,
    modified_at timestamp,
    post_id bigint,
    user_id varchar(255),
    content varchar(255),
    primary key (comment_id)
);

--create post table
create table post (
    like_count integer not null,
    recruit boolean not null,
    created_at timestamp not null,
    modified_at timestamp,
    post_id bigint generated by default as identity,
    user_id varchar(255),
    city varchar(255) check (city in ('Seoul','Busan','Daegu','Gwangju','Ulsan','Daejun','Gyeonggi','Gangwon','Chungnam','Chungbuk','Gyeongbuk','Gyeongnam','Jeonbuk','Jeonnam','Jeju')),
    content varchar(255),
    sport varchar(255) check (sport in ('Badminton','Baseball','Basketball','Billiards','Bowling','Soccer','Running')),
    title varchar(255),
    primary key (post_id)
);

-- create users table
create table users (
    user_id varchar(255),
    user_name varchar(255),
    nick_name varchar(255),
    created_at timestamp not null,
    modified_at timestamp,
    primary key (user_id)
);

alter table if exists comment
add constraint comment_post
foreign key (post_id)
references post;

alter table if exists comment
add constraint comment_user
foreign key (user_id)
references users;

alter table if exists post
add constraint post_user
foreign key (user_id)
references users;